trigger: none

resources:
  pipelines:
    - pipeline: BuildPipeline
      source: Build pipeline
      trigger: true

stages:
- stage: Deploy
  jobs:
  - job: DeployDatabase
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: BuildPipeline
      artifact: ProjectDB
      
    - task: SqlAzureDacpacDeployment@1
      displayName: 'Azure SQL DacpacTask'
      inputs:
        azureSubscription: 'Azure subscription 1 (3ec5c0ac-5b6f-4a11-9982-b335e0ba3b94)'
        ServerName: 'employee-system-sql.database.windows.net'
        DatabaseName: 'employee-system-db'
        SqlUsername: sqladmin
        SqlPassword: 'Password@123'
        DacpacFile: '$(Pipeline.Workspace)/BuildPipeline/ProjectDB/ProjectDatabase.dacpac'

  - job: DeployWebAPI
    steps:  
    - download: BuildPipeline
      artifact: WebAPI
      
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Azure subscription 1 (3ec5c0ac-5b6f-4a11-9982-b335e0ba3b94)'
        appName: 'employee-system-api'
        package: '$(Pipeline.Workspace)/BuildPipeline/WebAPI/WebAPI.zip'
        deploymentMethod: 'zipDeploy'
  - job: DeployAngularApp
    steps:
    - download: BuildPipeline
      artifact: UI
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '$(Pipeline.Workspace)/BuildPipeline/UI/UI.zip'
        destinationFolder: '$(Pipeline.Workspace)/ui-files'
        cleanDestinationFolder: true
        overwriteExistingFiles: true

    - task: AzureStaticWebApp@0
      inputs:
        workingDirectory: '$(Pipeline.Workspace)'
        app_location: 'ui-files/ui/browser'
        skip_app_build: true
        azure_static_web_apps_api_token: 'dfecf923d0bafa0604b826f2ff23c1543e806d351237b84d942544969ea90a8f05-c3228320-6fbd-4dfc-9b78-f92f643f60aa00f132601df2610f'
